### ISSUE TITLE
我一直出現SocketError

### ISSUE THREAD

**Issue by kay54068** [JustJJImmy/ntp_for_qt#1]
您好，我是使用您的範例，一直出現SocketError，請問您覺得是哪裡出問題?

NTPClient::timerEvent timeout: 1542100342155 , for: "pool.ntp.org"
NTPClient::onNtpError:  QAbstractSocket::SocketError(22) , failed times: 81

information:
QT version: 5.11.2
platform: Windows

**Comment by JimmyJay2015** [comment]
这个 bug 我已经发现，我会尽快修复。

原因是我对 ntp 请求做了超时限制，4s 内没响应会断开 socket 重新发起请求。
然而我对网络环境预估不足，4s 超时偏短、连续失败后的增量间隔也偏短，导致如果 ntp server 访问失败的话，会不断重发。

**Comment by JimmyJay2015** [comment]
建议您先修改 
ntpclient.cpp
#define UDP_TIMEOUT                 30000

const qint32 gDelayResendIntervals[UDP_RESEND_INTERVAL_COUNT]
    = {2000, 5000, 10000, 15000, 18000, 20000};
}

**Comment by kay54068** [comment]
很常出現沒傳Transmit Timestamp:
![default](https://user-images.githubusercontent.com/3054544/48423793-44ccff80-e79c-11e8-8d41-e7b6a89115fa.png)

**Comment by JimmyJay2015** [comment]
请求包丢失 Transmit Timestamp 的问题转至 #2 
https://github.com/JustJJImmy/ntp_for_qt/issues/2
